# Generated by Django 4.0.6 on 2022-07-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='фамилия')),
                ('department', models.CharField(blank=True, choices=[('development', 'разработки'), ('supply', 'снабжение'), ('marketing', 'маркетинг'), ('management', 'управление'), ('production', 'производство'), ('sales', 'продажи')], max_length=12, null=True, verbose_name='отдел')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='должность')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='телефон')),
                ('phone_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='телефон 2')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='почта')),
                ('email_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='почта 2')),
                ('actual', models.BooleanField(default=True, verbose_name='актуальный')),
                ('emailing', models.BooleanField(default=True, verbose_name='рассылка')),
                ('created', models.DateField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated', models.DateField(auto_now=True, verbose_name='дата обновления')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Контакт клиента',
                'verbose_name_plural': 'Контакты клиента',
                'permissions': (('manage_contact', 'Can manage contact'),),
            },
        ),
    ]
