# Generated by Django 4.0.6 on 2022-07-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('priority', models.BooleanField(default=False, verbose_name='приоритет')),
                ('country', models.CharField(blank=True, choices=[('ru', 'Россия'), ('by', 'Беларусь'), ('ua', 'Украина'), ('az', 'Азербайджан'), ('am', 'Армения'), ('kz', 'Казахстан'), ('uz', 'Узбекистан'), ('md', 'Молдавия')], default='ru', max_length=2, null=True, verbose_name='страна')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес 2')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='сайт')),
                ('sap', models.CharField(blank=True, max_length=255, null=True, verbose_name='SAP')),
                ('created', models.DateField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated', models.DateField(auto_now=True, verbose_name='дата обновления')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'permissions': (('manage_customer', 'Can manage customer'),),
            },
        ),
    ]
