# Generated by Django 4.0.6 on 2022-07-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Actives', (('SA', 'Skin Actives'), ('HA', 'Hair Actives'))), ('MicroProtection', (('SP', 'Skin Protection'), ('PP', 'Product Protection'))), ('Sun&Fun', (('SUN', 'Sun Care'), ('FUN', 'Functionals'))), ('Botanicals&Colors', (('BOT', 'Botanicals'), ('COL', 'Colors')))], max_length=3, verbose_name='категория')),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True, verbose_name='подкатегория')),
                ('phn', models.CharField(blank=True, max_length=255, null=True, verbose_name='группа')),
                ('priority', models.CharField(blank=True, max_length=255, null=True, verbose_name='приоритет')),
                ('number', models.IntegerField(verbose_name='номер')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('properties', models.TextField(blank=True, null=True, verbose_name='свойства')),
                ('inci', models.TextField(blank=True, null=True, verbose_name='inci')),
                ('dosage', models.CharField(blank=True, max_length=255, null=True, verbose_name='ввод')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='цвет')),
                ('form', models.CharField(blank=True, max_length=255, null=True, verbose_name='форма')),
                ('solubility', models.CharField(blank=True, max_length=255, null=True, verbose_name='растворимость')),
                ('registration', models.CharField(blank=True, max_length=255, null=True, verbose_name='регистрация')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('actual', models.BooleanField(default=True, null=True, verbose_name='актуальный')),
                ('sanctioned', models.CharField(choices=[('Unknown', 'не проверен'), ('True', 'да'), ('False', 'нет')], default='Unknown', max_length=7, verbose_name='санкционный')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
